services:
    phlexible_indexer_page.element_indexible_voter:
        class: Phlexible\Bundle\IndexerPageBundle\Indexer\IndexibleVoter\ElementIndexibleVoter
        public: false
        arguments:
            - "@phlexible_element.element_service"
            - "@logger"
        tags:
            - {name: monolog.logger, channel: indexer}

    phlexible_indexer_page.node_indexible_voter:
        class: Phlexible\Bundle\IndexerPageBundle\Indexer\IndexibleVoter\NodeIndexibleVoter
        public: false
        arguments:
            - "@logger"
        tags:
            - {name: monolog.logger, channel: indexer}

    phlexible_indexer_page.siteroot_indexible_voter:
        class: Phlexible\Bundle\IndexerPageBundle\Indexer\IndexibleVoter\SiterootIndexibleVoter
        public: false
        arguments:
            - "@logger"
        tags:
            - {name: monolog.logger, channel: indexer}

    phlexible_indexer_page.indexible_voter:
        class: Phlexible\Bundle\IndexerPageBundle\Indexer\IndexibleVoter\ChainIndexibleVoter
        public: false
        arguments:
            -
                - "@phlexible_indexer_element.element_indexible_voter"
                - "@phlexible_indexer_element.node_indexible_voter"
                - "@phlexible_indexer_element.siteroot_indexible_voter"
